### ISSUE TITLE
dendrograms, row/column group sizes?

### ISSUE THREAD

**Issue by paul-shannon** [MaayanLab/clustergrammer-widget#1]
The jupyter widget version of clustergrammer is a very nice piece of work.  Congratulations.
I am not yet clear on how to display row and column dendrograms, nor how to adjust row group and column group sizes, when running the sample notebook:

  Running_clustergrammer_widget.ipynb   

Can you point me to documentation I may have missed, or otherwise help out?

**Comment by cornhundred** [comment]
Thanks. Are you using Mozilla as your browser? In my experience, Mozilla does not render SVG paths correctly and the grey trapezoids that display the dendrogram are made with SVG paths. If you are using Mozilla you can try Chrome or Safari. If that is not the problem, then can you send me a screenshot? Also, the sliders on the left-sidebar can be used to control the size of the dendrograms.
-Nick

**Comment by paul-shannon** [comment]
Hi Nick,

You got it right: the dendrograms work fine in chrome.  

Two new questions:

1) Are hierarchical dendrograms available?  I think you once told me that they are

2) We would like to select rows and columns by name, via a python function call from the notebook, which resolves to a javascript function in the widget.  Similarly, we want to be able to query the current selection state of the widget from python.  The cyjs widget - should have  the nbextension version ready later this week - has quite a few operations like this.  I try to make all the interactive gestures also available as function calls.

My collaborators were pretty impressed by the clustergrammer widget demo I did today.

 - Paul

**Comment by cornhundred** [comment]
Paul, 

I am glad the widget is working well. You can adjust the size of the dendrogram-groups (the grey trapezoids) using the sliders in the left sidebar: 'Row Group Size' and 'Column Group Size'. 

Currently, there is only one-way communication from Python to JavaScript, but I would like to add JavaScript -> Python communication too. For instance, it would be nice to press a front-end button to modify clustering parameters (e.g. distance metric). In your question do you mean that: 1) you want to filter for a subset of rows/columns by passing a list to the Python function and 2) you want to export the current matrix (in its current state) from the JavaScript to Python as a DataFrame. 

I look forward to seeing how you set up these operations on the cyjs widget. 

-Nick

**Comment by cornhundred** [comment]
Paul, 

The widget now works with nbviewer 

http://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb 

Nick

**Comment by paul-shannon** [comment]
Thanks, Nick!

For what it's worth, my current strategy (and my current wish for clustergrammer) is described in issue [6](https://github.com/MaayanLab/clustergrammer/issues/6).  I am very keen to try that out when you have the time to work on it.  Meanwhile, clustergrammer gets better and better!

**Comment by cornhundred** [comment]
Hey Paul,

Thanks, hopefully I can have a go at it this week. I'll keep you posted.

Nick
