### ISSUE TITLE
run_clustering=False results in unrepresentable widget

### ISSUE THREAD

**Issue by IanMcDowell** [MaayanLab/clustergrammer-widget#5]
The arguments `run_clustering=False` or `dendro=False` in `net.cluster()` result in a non-viewable widget.

**Comment by cornhundred** [comment]
Hi, 

Sorry for the long delay, but we released a new version 1.13.3 that should correctly render a non-clustered matrix (e.g. `run_clustering=False` in Clustergrammer-PY). 

Let us know if that works.

Best,
Nick

**Comment by IanMcDowell** [comment]
It works for me. Thanks for the update!

On Wed, Mar 14, 2018 at 5:28 PM, Nicolas Fernandez <notifications@github.com
> wrote:

> Hi,
>
> Sorry for the long delay, but we released a new version 1.13.3 that should
> correctly render a non-clustered matrix (e.g. run_clustering=False in
> Clustergrammer-PY).
>
> Let us know if that works.
>
> Best,
> Nick
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MaayanLab_clustergrammer-2Dwidget_issues_5-23issuecomment-2D373180773&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=lqUYV1EqLjBHkMjMVn1itf-Do_V9RF37klFGwtVy3Oc&s=a_b6ZVzkLm9xcIRvyG-TJn5laUfCW6I9KBVzhcuT-RY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9LTGF1QNtGgu3ghcAQLBS8BszDF-2Dks5teYtigaJpZM4RjoJU&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=lqUYV1EqLjBHkMjMVn1itf-Do_V9RF37klFGwtVy3Oc&s=sEPrJQ9tSCXDxT1PoX1p-VqN9omswDs21li9Q5huUDQ&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University
